"""
Export the course to TypeScript for the Remotion video.

The video draws the same course as the landing page and the social card, so the
geometry comes from scripts/course.py rather than being redrawn by hand. The
terrain is static, so it travels as one block of SVG markup; the legs, controls
and labels travel as numbers, because the video animates them.

    python3 scripts/export_course_ts.py

Writes video/src/course.ts.
"""

import json
import math
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import course as C  # noqa: E402


def main():
    svg = C.svg(cleared=0, locked_opacity=".5")
    terrain = re.search(r'<g class="terrain">(.*?)</g>', svg, re.S).group(1)
    terrain = re.sub(r"\s*\n\s*", "", terrain)

    sx, sy = C.START
    ang = math.atan2(C.CONTROLS[0][1] - sy, C.CONTROLS[0][0] - sx)
    start_tri = [
        [round(sx + C.R_START * math.cos(ang + k), 1),
         round(sy + C.R_START * math.sin(ang + k), 1)]
        for k in (0, 2.24, -2.24)
    ]

    data = {
        "FIELD": list(C.FIELD),
        "LEGS": [[round(v, 1) for v in leg] for leg in C.legs()],
        "CONTROLS": [list(c) for c in C.CONTROLS],
        "LABELS": [[round(x, 1), round(y, 1)] for x, y in C.label_positions()],
        "START": list(C.START),
        "START_TRI": start_tri,
        "FINISH": list(C.FINISH),
        "R_CTRL": C.R_CTRL,
        "R_FINISH": C.R_FINISH,
        "R_FINISH_IN": C.R_FINISH_IN,
    }

    out = ["// Generated by scripts/export_course_ts.py from scripts/course.py.",
           "// Do not edit by hand: change the course there and re-export.", ""]
    for k, v in data.items():
        out.append(f"export const {k} = {json.dumps(v)} as const;")
    out.append("")
    out.append("export const TERRAIN_SVG = " + json.dumps(terrain) + ";")
    out.append("")

    path = os.path.join(ROOT, "video", "src", "course.ts")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(path, ROOT)}: {len(data['LEGS'])} legs, "
          f"terrain {len(terrain) // 1024} KB")


if __name__ == "__main__":
    main()
