"""
Cut the soundtrack fragment and fit the video's timing to it.

    python3 scripts/fit_music.py path/to/track.mp3

Writes video/public/music.m4a and video/src/music.ts. The video reads its scene
lengths and its beat grid from music.ts, so scene cuts land on downbeats and the
state changes inside scenes - a leg inking, a verdict landing - land on beats.

How the fragment is chosen
--------------------------
The minute is taken from the end of the track, 132.0 s to 192.0 s, because the
end of this track has exactly the shape the video needs:

    137.88 s  drums re-enter after a dip    -> the second scene begins
    182.69 s  the music drops to near quiet -> "The page is down"
    188.27 s  the strongest hit in the track -> the name appears
    192.0 s   the tail has decayed to silence -> the video ends with the song

The breakdown is the sync that matters. The scene where a source goes offline
plays over the moment the music drops out, so the outage is something you hear.
That needed one change to the edit: "verdicts arrive in any order" now comes
before "the page is down", so the winner is called at full energy and the
reassurance that nothing is lost sits in the quiet before the end card.

The anchors above were measured, not chosen by ear: onset strength for the hits,
the steepest loudness fall for the breakdown, and a beat tracker for the grid.
Re-entry to breakdown is exactly 92 beats, 23 bars, which is how the downbeat
phase is fixed.

If the track changes, re-run the analysis described in RUN.md and update the
constants below; everything downstream regenerates from them.
"""

import json
import os
import subprocess
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FPS = 30
TOTAL = 1800

START = 132.0            # where the minute begins in the track, seconds
REENTRY = 137.879        # drums return: a downbeat
BREAKDOWN = 182.694      # the drop
FINAL_HIT = 188.267      # the strongest onset in the track
BEAT = 60.0 / 123.046875 # 0.4876 s at the tracked tempo

# Scene order. "order" now precedes "undetermined"; see the docstring.
SCENES = ["open", "gate", "course", "commit", "tribunal", "order", "undetermined", "end"]
# Relative weights for the scenes that are not pinned to an anchor, taken from
# the original cut so their pacing survives the refit.
FREE = {"gate": 210, "course": 270, "commit": 240, "tribunal": 360, "order": 210}


def rel_frame(t):
    return (t - START) * FPS


def downbeats():
    """Bar lines, phase-locked to the re-entry hit, over the whole minute."""
    bar = 4 * BEAT
    first = REENTRY - bar * np.floor((REENTRY - START) / bar)
    return [rel_frame(t) for t in np.arange(first, START + 60.0, bar)]


def beats():
    first = REENTRY - BEAT * np.floor((REENTRY - START) / BEAT)
    return [round(rel_frame(t), 2) for t in np.arange(first, START + 60.0 + 1e-9, BEAT)]


def fit():
    a = round(rel_frame(REENTRY))      # gate begins
    b = round(rel_frame(BREAKDOWN))    # undetermined begins
    c = round(rel_frame(FINAL_HIT))    # end card begins

    # spread gate..order across a..b in their original proportions, then snap
    # each inner cut to the nearest bar line
    names = ["gate", "course", "commit", "tribunal", "order"]
    weights = np.array([FREE[n] for n in names], dtype=float)
    cuts = a + np.cumsum(weights / weights.sum() * (b - a))[:-1]
    bars = np.array(downbeats())
    snapped = [int(round(bars[np.argmin(abs(bars - x))])) for x in cuts]

    bounds = [0, a, *snapped, b, c, TOTAL]
    durs = [bounds[i + 1] - bounds[i] for i in range(len(bounds) - 1)]
    assert sum(durs) == TOTAL and all(d > 0 for d in durs), durs
    return bounds, durs


def cut_audio(src):
    out = os.path.join(ROOT, "video", "public", "music.m4a")
    # A short fade at each edge stops a click; the tail has already decayed to
    # silence by 192 s, so the out-fade only tidies the last samples. Loudness
    # is normalised to -14 LUFS, the level X, YouTube and most players target.
    af = ("afade=t=in:st=0:d=0.15,afade=t=out:st=59.6:d=0.4,"
          "loudnorm=I=-14:TP=-1.0:LRA=11")
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", str(START), "-t", "60",
                    "-i", src, "-vn", "-af", af, "-ar", "48000", "-ac", "2",
                    "-c:a", "aac", "-b:a", "256k", out], check=True)
    return out


def main(src):
    bounds, durs = fit()
    ts = os.path.join(ROOT, "video", "src", "music.ts")
    with open(ts, "w") as f:
        f.write("// Generated by scripts/fit_music.py. Do not edit by hand.\n")
        f.write(f"// Track window {START:.1f}s to {START + 60:.1f}s, 123 BPM.\n\n")
        f.write(f"export const SCENE_ORDER = {json.dumps(SCENES)} as const;\n")
        f.write(f"export const DURATIONS = {json.dumps(durs)} as const;\n")
        f.write(f"export const BEATS: number[] = {json.dumps(beats())};\n")
        f.write(f"export const BEAT_FRAMES = {BEAT * FPS:.4f};\n")
    out = cut_audio(src)
    print("scene bounds (frames):", bounds)
    print("durations:", durs)
    for name, s in zip(SCENES, bounds):
        print(f"  {name:13s} starts {s / FPS:6.2f}s")
    print("wrote", os.path.relpath(ts, ROOT), "and", os.path.relpath(out, ROOT))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "Vorawa_rts.mp3")
